version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gold_investment_platform
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.example
    environment:
      DATABASE_HOST: db
    ports:
      - '3000:3000'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1
    ports:
      - '3001:80'
    depends_on:
      - backend

volumes:
  db_data: {}
